name: Newman CI - Run Postman collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install newman newman-reporter-htmlextra --no-save

      - name: Run Newman collection
        run: |
          mkdir -p reports
          npx newman run ./postman/collection.json \
            -e ./postman/environment.json \
            -r cli,htmlextra,junit \
            --reporter-htmlextra-export ./reports/report.html \
            --reporter-junit-export ./reports/junit.xml

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/
